project: bubula2
pyenv: env
static_relative_dir: static
bundle_and_minify:
  static/js/pack.js:
    - static/js/plugins.js
    - static/js/main.js
  static/css/pack.css:
    - static/css/normalize.css
    - static/css/main.css
    - static/css/ir-sprites.css
  static/comics/js/single-pack.js:
    - static/comics/js/dropdown.js
    - static/comics/js/single.js
  static/comics/css/single-pack.css:
    - static/comics/css/dropdown.css
    - static/comics/css/single.css
    - static/comics/css/single-ir-sprites.css

hosts:
  - %HOST%

paths:
  yuicompressor_path: '/usr/local/bin/yuicompressor-2.4.7.jar'
  apps_path: %HOST_APPS_PATH%
  static: '{apps_path}/bubula2_static'
  media: '{apps_path}/bubula2_media'
  path: '{apps_path}/bubula2'
  restart: '{path}/apache2/bin/restart'
